### ISSUE TITLE
pre-trained

### ISSUE THREAD

**Issue by Jorewang** [Clarifai/few-shot-ctm#11]
The res-net used in code is  from pytorch official webiste,which pre-trained from image-net. Is it fair compared to other models?

**Comment by YorksonChang** [comment]
But you can turn off the pre-trained mode in the code, right? 
Don't know if the author used the pre-trained model in the paper:)

**Comment by deigen** [comment]
I was able to dig into finding the pretraining code, and was able to find scripts for that, which I have pushed to the "pretrain" branch.

Unfortunately, I was not able to find exactly the code that was used in our final experiments, but was able to find enough to verify that pretraining used the correct class set, and did not use any other pretrained weights.  There are details around the number of resnet layers used (3 or 4) that I wasn't able to find, and may even have been deleted at this point, but was able to get the script running again.  Hope this is able to help.
