### ISSUE TITLE
how long we need to train？

### ISSUE THREAD

**Issue by valencebond** [Clarifai/few-shot-ctm#2]
i just run the command line` python main.py --yaml_file configs/demo/mini/20way_1shot.yaml`，and change` self.ctrl.device = 'cuda' , ctrl.device = 'cuda'`.The code is almost running 48 hours in one GPU. And just get 

> Evaluating at epoch 216, step 212, with eval_length 600 ... (be patient)
		Current  accuracy is 0.1530 < previous best accuracy is 0.1740 (ep55, iter212)
Can you give me some constructive advice?

**Comment by hli2020** [comment]
I am reproducing the model and would get back to you asap. For details, please refer to [this](https://github.com/Clarifai/few-shot-ctm/issues/4#issuecomment-532638228).
