### ISSUE TITLE
it seems difficult to reproduce

### ISSUE THREAD

**Issue by yanglilian** [Clarifai/few-shot-ctm#5]
I run all the possible config in the code you provide with a 5way-1shot setting on mini-imagenet, but result is far from you reported in the paper.
And when  i run with resnet backbone, the code seems to download pretrain model from pytorch official website, so I doubt the you really get the 62.05 without augmentation in 5way-1shot?

**Comment by hli2020** [comment]
I am re-training the pre-trained model. Seems the problem lies in here. Please refer to [this](https://github.com/Clarifai/few-shot-ctm/issues/4#issuecomment-532638228) and stay tuned.
